#!/usr/bin/env bash                                                             
# hopefully redirect                                                            

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo -e "                                                                       
ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "
frontend myitbuddy.tech
\tbind *:80
\tdefault_backend web_servers
backend web_servers
\tbalance roundrobin
\tserver 1828-web-01 34.73.254.4:80 check
\tserver 1828-web-02 3.82.35.197:80 check
" >> /etc/default/haproxy.cfg
sudo service haproxy restart
