#!/usr/bin/env bash
# prints replys removes
clean_up() {
     # Perform program exit housekeeping
     echo "I hate the kill command" 
     rm "/var/run/holbertonscript.pid"
     exit 
     }
trap clean_up SIGQUIT SIGTERM
trap "echo Y U no love me?!" SIGINT
echo $$ > /var/run/holbertonscript.pid
while true
    do
     echo "To infinity and beyond"
     sleep 2
    done
