#!/usr/bin/env bash
# prints clock
h="0"
while [ $h -lt 12 ]
    do
        echo "Hour: $h"
        m="1"
        while [ $m -lt 60 ]
            do
                echo "$m"
                m=$((m+1))
            done
    h=$((h+1))
done
