#!/usr/bin/env bash
# checks file stuff
F="holbertonschool"
if [ -e $F ]
    then
        echo "$F file exists"
    if [ -s $F ]
        then
            echo "$F file is empty"
        else
            echo "$F file is not empty"
    fi
    if [ -f $F ]
        then
            echo "$F is regular file"
    fi
else
    echo "$F file does not exist"
fi
